server:
  port: 8080

spring:
  datasource:
    # Thay đổi url, username, password phù hợp với máy bạn
    url: jdbc:mysql://localhost:3306/shoe_store_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Abcd1234@#$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Cẩn thận: Tự động sửa bảng DB khi sửa code Java
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

        # Cấu hình JWT
app:
  jwt:
    # Chuỗi bí mật dùng để ký token (Tuyệt đối không để lộ)
    # Bạn có thể gõ một chuỗi bất kỳ dài dài một chút (ít nhất 32 ký tự)
    secret: "DayLaKhoaBiMatCuaShoeStoreVuiLongKhongHackEmNhe123456789@"

    # Thời gian hết hạn của Access Token (tính bằng mili giây)
    # 86400000 ms = 24 giờ (Để dài test cho dễ, sau này chỉnh xuống 15p sau)
    expiration: 86400000
    
    # Thời gian hết hạn của Refresh Token (7 ngày)
    refresh-expiration: 604800000